/**
 * Evidence upload, sealing and access.
 *
 * ── Why the transport changed ──────────────────────────────────────────────
 * The geo-legal module took evidence as base64 inside a JSON body. Screen C5
 * attaches a 24.8 MB video with per-file progress, which that cannot do: base64
 * inflates by a third, gives no progress, cannot resume, and breaches the JSON
 * body limit. So the flow is presign → direct PUT → commit.
 *
 * ── What "Sealed" means ────────────────────────────────────────────────────
 * On commit the server reads the stored object, hashes it, and compares that to
 * the SHA-256 the client declared. Only then is `sealed_at` stamped. That single
 * server-side timestamp is what C5, C9, D3, D11 and D12 all render — there is no
 * client-supplied seal time anywhere, because a timestamp the client chooses
 * proves nothing about when the file arrived or whether it changed.
 *
 * A mismatch is refused, not logged and accepted: the whole trust story on D3
 * rests on "Nothing has changed since", and a file we cannot vouch for must not
 * be able to claim that.
 *
 * ── Revision 2 (docs/INCIDENT_MODULE_PLAN.md §7.1, §7.3, §7.9, D22) ────────
 *   • **Ownership.** Presign used to accept any `reportId` or `draftId`, so any
 *     member could attach — and seal — files onto someone else's report, and the
 *     draft file list answered for any draft UUID. Every entry point now resolves
 *     the target through the caller's own draft or report, or answers 404.
 *   • **One lock with filing.** Presign, commit and remove lock the same draft row
 *     filing locks (`SELECT … FOR UPDATE`). No file can be attached, sealed or
 *     removed while its draft is being filed, the per-report caps cannot be raced
 *     past, and once filing has consumed a draft every later call on it is a 404.
 *     The hash itself is computed *before* the lock is taken, so a slow download
 *     of a large file never holds up the draft.
 *   • **Moderation state (D22).** A file has its own `moderation_state`, written
 *     explicitly at presign: `pending` (a draft's files are re-stated by
 *     visibility at filing), or `approved` for a private report, which is never
 *     sent to the AI (D3). Non-owners are sent a URL only for an approved file;
 *     a pending one is listed "Awaiting review" with no URL; a rejected file or a
 *     failed upload is not listed to them at all.
 *   • **Late files.** A file sealed onto an already-filed moderated report
 *     queues an `evidence` run in the sealing transaction when no queued run
 *     would otherwise read it, so it is assessed rather than left waiting for a
 *     moderator (§5.1). A report still waiting for the human check its last
 *     resubmission promised gets a `resubmitted` run instead (D19, review R1),
 *     and an urgent report keeps its urgent priority and short retry budget
 *     (D5/D21, review R2).
 *
 * ── Approval is bound to the bytes that are served (review R5) ────────────
 * The AI assesses a photo through its preview, and the preview is generated by
 * the client — it was never hashed or tied to the original, while non-owners
 * were served the original. Worse, the presigned PUT URLs stay valid for
 * `S3_PRESIGN_EXPIRES_SECONDS`, so both objects could be replaced *after* an
 * approval. Three rules close that:
 *
 *   1. **Sealing moves the bytes.** Commit reads the original (and the preview,
 *      when one was uploaded), hashes both, and copies each to a fresh
 *      `sealed/<uuid>` key that no presigned PUT was ever issued for — the copy
 *      conditional on the ETag that was hashed, so a re-PUT in between fails the
 *      seal instead of sealing unverified bytes. The row is repointed at the
 *      sealed keys (with `thumb_sha256`), and the upload keys are deleted after
 *      the commit. A failed copy marks the row `failed`; nothing is half-moved.
 *   2. **An approval names its scope.** `approveEvidence` records `full` (the
 *      original was assessed) or `thumbnail` (only the sealed preview was).
 *   3. **Non-owners get exactly the approved bytes.** `thumbnail` scope serves
 *      `thumbUrl` alone with `fullResolutionPending`; `full` serves both. Owners
 *      and staff always get both. The rule is `evidenceAccessFor` in
 *      `report_visibility.ts`, applied by `toView` itself for a member audience.
 */

import crypto from "crypto";
import { Op, QueryTypes, type Transaction } from "sequelize";
import sequelize from "@/config/database.config";
import env from "@/config/env.config";
import logger from "@/utils/logger.util";
import { nowIso } from "@/models/model_options";
import { Report, ReportDraft, ReportEvidence } from "@/models/report.model";
import s3Service, { ObjectTooLargeError } from "@/services/s3.service";
import { enqueueRun, maxAttemptsFor } from "@/services/moderation_enqueue";
import { pokeModeration } from "@/services/moderation_signal";
import { evidenceAccessFor, type EvidenceAccess } from "@/services/report_visibility";
import { lockedTransaction } from "@/services/report_tx";
import { HttpError, badRequest, notFound } from "@/middlewares/error.middleware";
import { sniffMediaType } from "@/utils/binary.util";
import {
  isAwaitingResubmissionCheck,
  needsModeration,
  planLateEvidenceRun,
  type EvidenceApprovedScope,
  type EvidenceModerationState,
} from "@/types/moderation.interface";
import type {
  EvidenceKind,
  EvidenceView,
  PresignEvidenceDto,
} from "@/types/report.interface";

/** Which MIME types each attachment kind accepts. */
const KIND_MIMES: Record<EvidenceKind, RegExp> = {
  photo: /^image\/(jpeg|png|webp|heic|heif)$/,
  video: /^video\/(mp4|quicktime|webm)$/,
  audio: /^audio\/(mpeg|mp4|aac|wav|m4a|x-m4a)$/,
  document: /^application\/pdf$/,
};

/** Human labels for D3's per-file rows and C9's sealed list. */
const KIND_LABELS: Record<EvidenceKind, string> = {
  photo: "Photo",
  video: "Video",
  audio: "Audio",
  document: "Document",
};

/**
 * Who a file row is being projected for.
 *   • `staff` — moderators and internal callers: everything, with its state.
 *   • `owner` — the file's own author: everything, with its state.
 *   • `member` — anyone else: an approved file, without its state, and only the
 *     bytes its approval covered (`approved_scope`, review R5).
 */
export type EvidenceAudience = "staff" | "owner" | "member";

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function formatDuration(ms: number): string {
  const total = Math.round(ms / 1000);
  const minutes = Math.floor(total / 60);
  const seconds = total % 60;
  return `${minutes}:${String(seconds).padStart(2, "0")}`;
}

const DRAFT_GONE = "That draft no longer exists.";
const REPORT_GONE = "That report is not available.";

/**
 * The largest preview the commit will read. A preview is a device-made JPEG of a
 * few hundred KB; anything near this is not one, and the PUT URL does not bound
 * what gets uploaded (R5).
 */
const PREVIEW_MAX_BYTES = 5 * 1024 * 1024;

/** Preview formats worth sealing: what the client makes, and what the AI reads. */
const PREVIEW_MEDIA_TYPES = new Set(["image/jpeg", "image/png", "image/webp"]);

/** Where sealed objects live. No presigned PUT is ever issued under it (R5). */
const SEALED_PREFIX = "sealed";

/** The upload key of a row's preview slot, as presign issued it. */
function uploadPreviewKey(storageKey: string): string {
  return storageKey.replace(/\.[^./]+$/, "") + "-thumb.jpg";
}

/** A fresh sealed key pair. The extension is kept so plain reads infer a type. */
function sealedKeysFor(uploadKey: string): { original: string; preview: string } {
  const extension = /\.([a-z0-9]{1,16})$/i.exec(uploadKey)?.[1]?.toLowerCase() ?? "bin";
  const id = crypto.randomUUID();
  return {
    original: `${SEALED_PREFIX}/${id}.${extension}`,
    preview: `${SEALED_PREFIX}/${id}-thumb.jpg`,
  };
}

function sha256Hex(bytes: Buffer): string {
  return crypto.createHash("sha256").update(bytes).digest("hex");
}

/** What `approveEvidence` approves, and at which scope (D22, R5). */
export interface ApproveEvidenceInput {
  reportId: string;
  /** Specific files, or every pending file of the report (a private report's sweep). */
  ids: readonly string[] | "all_pending";
  /**
   * `full` when the original itself was assessed (a human; the AI reading the
   * sealed original); `thumbnail` when only the sealed preview was.
   */
  scope: EvidenceApprovedScope;
}

/**
 * Approve evidence at a scope — the one writer of `approved_scope` for files
 * that were pending (D22, review R5). The pipeline calls it with `thumbnail`
 * when the AI assessed only the sealed preview and `full` when it assessed the
 * original; a private report's files are `full` (nobody but the owner and staff
 * ever sees them); human approval (Phase 2) is `full`.
 *
 *   • pending                        → approved, at `scope`
 *   • approved at `thumbnail` + full → upgraded to `full`
 *   • approved at `full`             → untouched (never narrowed)
 *   • rejected                       → untouched (a human decided)
 *
 * The scope arithmetic is `mergeApprovedScope` (moderation.interface.ts),
 * restated in SQL so concurrent approvals cannot lose an upgrade. Lock the
 * report row first (the lock order every writer follows). Returns the ids that
 * changed.
 */
export async function approveEvidence(tx: Transaction, input: ApproveEvidenceInput): Promise<string[]> {
  if (input.ids !== "all_pending" && input.ids.length === 0) return [];
  const idFilter = input.ids === "all_pending" ? "" : "AND id IN (:ids)";
  const rows = await sequelize.query<{ id: string }>(
    `UPDATE report_evidence
        SET moderation_state = 'approved',
            approved_scope = CASE WHEN :scope = 'full' OR approved_scope = 'full'
                                  THEN 'full' ELSE 'thumbnail' END,
            updated_on = now()
      WHERE report_id = :reportId ${idFilter}
        AND (moderation_state = 'pending'
             OR (moderation_state = 'approved' AND :scope = 'full'
                 AND approved_scope IS DISTINCT FROM 'full'))
      RETURNING id`,
    {
      replacements: {
        reportId: input.reportId,
        scope: input.scope,
        ...(input.ids === "all_pending" ? {} : { ids: [...input.ids] }),
      },
      type: QueryTypes.SELECT,
      transaction: tx,
    },
  );
  return rows.map((row) => row.id);
}

/**
 * D19: does this report still owe the human check a human rejection promised?
 * The one query behind the edit path (`reportService.updateReport`), the
 * late-evidence path below (review R1), *Re-run AI* (`requestRerun`),
 * Reactivate and every run decision (`decisionTrigger`); the rule itself is the
 * pure `isAwaitingResubmissionCheck`. While it holds, any new run for the
 * report must be queued — and is decided — `resubmitted`, or the AI alone could
 * republish a report a human rejected. Call with the report row locked.
 *
 * Review Q7: no short-circuit on `resubmission_count` any more. A rejected
 * report that Reactivate sent back owes the check with a count of 0, and only
 * the `resubmitted` run it queued says so. Only non-live reports reach the
 * query, and it is one indexed lookup.
 */
export async function awaitsResubmissionCheck(
  tx: Transaction,
  report: Pick<Report, "id" | "resubmission_count" | "moderation_state" | "approved_content_version">,
): Promise<boolean> {
  // The cheap refusal first, without a query: a live (or rejected, or
  // deactivated) report owes nothing to a run.
  if (report.moderation_state !== "pending" && report.moderation_state !== "held") return false;
  const rows = await sequelize.query<{ content_version: number | string }>(
    `SELECT content_version FROM moderation_runs
      WHERE target_type = 'report' AND target_id = :reportId AND "trigger" = 'resubmitted'
      ORDER BY created_at DESC
      LIMIT 1`,
    { replacements: { reportId: report.id }, type: QueryTypes.SELECT, transaction: tx },
  );
  const last = rows[0];
  return isAwaitingResubmissionCheck(report, last ? Number(last.content_version) : null);
}

class EvidenceService {
  /** True when object storage is configured; otherwise uploads cannot be offered. */
  get isStorageReady(): boolean {
    return s3Service.isEnabled;
  }

  /**
   * Step 1 — create the row and hand back a URL to PUT to.
   *
   * The key is generated server-side from a UUID and never from a client filename,
   * which removes traversal and overwrite as a class of problem. The target must
   * be the caller's own draft or report (§7.9).
   */
  async presign(
    userId: string,
    target: { reportId?: string; draftId?: string },
    dto: PresignEvidenceDto,
  ): Promise<{
    evidenceId: string;
    uploadUrl: string;
    headers: Record<string, string>;
    /** Second slot for a preview image. Null for kinds that have no preview. */
    thumbUploadUrl: string | null;
    thumbHeaders: Record<string, string> | null;
  }> {
    if (!this.isStorageReady) {
      throw badRequest(
        "File uploads are not configured on this server. Set STORAGE_DRIVER=s3.",
      );
    }

    const pattern = KIND_MIMES[dto.kind];
    if (!pattern.test(dto.mime)) {
      throw badRequest(`A ${dto.kind} cannot be a ${dto.mime} file.`);
    }
    if (dto.bytes > env.storage.maxUploadBytes) {
      throw badRequest(
        `That file is larger than the ${Math.floor(env.storage.maxUploadBytes / 1024 / 1024)} MB limit.`,
      );
    }

    const extension = dto.mime.split("/")[1]?.replace(/[^a-z0-9]/gi, "") || "bin";
    const objectId = crypto.randomUUID();
    const storageKey = `evidence/${userId}/${objectId}.${extension}`;

    /*
     * Photos and videos get a second slot for a preview.
     *
     * Generated on the device, not here. Two reasons, and the second is the one
     * that decides it:
     *   • The server never has to decode user-supplied media. Image and video
     *     parsers are a well-worn path to remote code execution, and a service that
     *     stores evidence for people at risk is the wrong place to open one.
     *   • The device already holds the full-resolution original, so resizing there
     *     costs one decode it was doing anyway rather than a round trip.
     *
     * Always JPEG: it is what the client produces, and pinning the type means the
     * signature and the eventual PUT cannot disagree.
     */
    const wantsThumb = dto.kind === "photo" || dto.kind === "video";
    const thumbKey = wantsThumb ? uploadPreviewKey(storageKey) : null;

    const row = await lockedTransaction(async (transaction) => {
      // Resolve — and lock — the caller's own target. The lock also serialises
      // the per-report caps below, which two concurrent presigns used to race.
      let scope: { report_id: string } | { draft_id: string };
      let moderationState: EvidenceModerationState = "pending";
      if (target.draftId) {
        const draft = await ReportDraft.findOne({
          where: { id: target.draftId, user_id: userId },
          transaction,
          lock: transaction.LOCK.UPDATE,
        });
        if (!draft) throw notFound(DRAFT_GONE);
        scope = { draft_id: draft.id };
      } else if (target.reportId) {
        const report = await Report.findOne({
          where: { id: target.reportId, user_id: userId },
          transaction,
          lock: transaction.LOCK.UPDATE,
        });
        if (!report || report.deleted_at) throw notFound(REPORT_GONE);
        if (report.moderation_state === "deactivated") {
          throw new HttpError("This report was taken down, so files can't be added to it.", 409);
        }
        // D3: a private report's files are never sent to the AI.
        moderationState = needsModeration(report) ? "pending" : "approved";
        scope = { report_id: report.id };
      } else {
        throw badRequest("Attach the file to a draft or a report.");
      }

      // Per-report caps, so presign cannot be used as free storage.
      const siblings = await ReportEvidence.findAll({ where: scope, transaction });
      if (siblings.length >= env.reports.maxEvidencePerReport) {
        throw badRequest(
          `A report can carry at most ${env.reports.maxEvidencePerReport} files.`,
        );
      }
      const totalBytes = siblings.reduce((sum, item) => sum + item.bytes, 0) + dto.bytes;
      if (totalBytes > env.reports.maxEvidenceBytesPerReport) {
        throw badRequest("Those files together are larger than one report can carry.");
      }

      return ReportEvidence.create(
        {
          report_id: "report_id" in scope ? scope.report_id : null,
          draft_id: "draft_id" in scope ? scope.draft_id : null,
          user_id: userId,
          kind: dto.kind,
          mime: dto.mime,
          bytes: dto.bytes,
          duration_ms: dto.durationMs ?? null,
          storage_key: storageKey,
          captured_at: dto.capturedAt ?? null,
          upload_state: "pending",
          sort_order: siblings.length,
          // Written explicitly — never the column default (§4.2, D22).
          moderation_state: moderationState,
          // A private report's file is approved as a whole: only its owner and
          // staff ever see it (R5).
          approved_scope: moderationState === "approved" ? "full" : null,
        },
        { transaction },
      );
    });

    const uploadUrl = await s3Service.getPresignedUploadUrl(storageKey, dto.mime);
    const thumbUploadUrl = thumbKey
      ? await s3Service.getPresignedUploadUrl(thumbKey, "image/jpeg")
      : null;

    return {
      evidenceId: row.id,
      uploadUrl,
      // Echoed so the client sets exactly what the signature covers — a mismatched
      // Content-Type makes S3 reject the PUT with an opaque 403.
      headers: { "Content-Type": dto.mime },
      thumbUploadUrl,
      thumbHeaders: thumbKey ? { "Content-Type": "image/jpeg" } : null,
    };
  }

  /**
   * Step 2 — verify, move and seal (review R5).
   *
   * This is the only place `sealed_at` is written. In order:
   *
   *   1. read the original (bounded by `MAX_UPLOAD_BYTES`) and compare its hash
   *      with the one the client declared — a mismatch is refused;
   *   2. read the preview, when the client says it uploaded one, and hash it
   *      (`thumb_sha256`). A preview that is missing, oversized or not an image
   *      is dropped — the file is sealed without one, so the AI cannot assess
   *      it and it waits for a moderator;
   *   3. copy both to fresh `sealed/…` keys, each copy conditional on the ETag
   *      that was hashed. A failed copy marks the row `failed`;
   *   4. under the draft/report lock presign and filing take, re-read the row
   *      and repoint it at the sealed keys. An already-sealed row (a concurrent
   *      commit won) is returned unchanged and this call's copies are removed;
   *   5. after the commit, delete the upload keys, which nothing references now.
   *
   * Steps 1–3 are network I/O and run outside any transaction, so a slow file
   * never holds a lock. Idempotent: a sealed row is returned as it is.
   */
  async commit(
    userId: string,
    evidenceId: string,
    dto: {
      sha256: string;
      capturedAt?: string;
      durationMs?: number;
      /** True when the client also PUT a preview to the second slot. */
      thumbUploaded?: boolean;
    },
  ): Promise<EvidenceView> {
    const row = await ReportEvidence.findOne({ where: { id: evidenceId, user_id: userId } });
    if (!row) throw badRequest("That upload is not recognised.");
    if (row.upload_state === "sealed") return this.toView(row, { audience: "owner" });
    if (!row.draft_id && !row.report_id) throw badRequest("That upload is not recognised.");

    // ── 1. The original ─────────────────────────────────────────────────────
    const uploadKey = row.storage_key;
    let original: { bytes: Buffer; etag: string | null };
    try {
      original = await s3Service.getObject(uploadKey, { maxBytes: env.storage.maxUploadBytes });
    } catch (err) {
      // A concurrent commit that already sealed the file deleted this upload
      // key (step 5) — its seal is the answer, not an error.
      const winner = await this.failUnlessSealed(row.id);
      if (winner) return this.toView(winner, { audience: "owner" });
      logger.warn("[evidence] could not read the uploaded object", {
        evidenceId,
        message: err instanceof Error ? err.message : String(err),
      });
      if (err instanceof ObjectTooLargeError) {
        throw badRequest(
          `That file is larger than the ${Math.floor(env.storage.maxUploadBytes / 1024 / 1024)} MB limit, so it has not been sealed.`,
        );
      }
      throw badRequest("That file did not finish uploading. Try again.");
    }
    const actualBytes = original.bytes.length;
    const actualHash = sha256Hex(original.bytes);

    if (actualHash.toLowerCase() !== dto.sha256.toLowerCase()) {
      // Refused, not accepted-with-a-warning. See the file header.
      await this.failUnlessSealed(row.id);
      logger.warn("[evidence] hash mismatch on commit — refusing to seal", { evidenceId });
      throw badRequest(
        "That file does not match what was uploaded, so it has not been sealed. Try attaching it again.",
      );
    }

    /*
     * ── 2. The preview ─────────────────────────────────────────────────────
     * Its upload key is derived from the original's, not stored at presign time:
     * writing it earlier would set `thumb_key` on a row whose preview may never
     * arrive, and `toView` treats a set key as a promise there is a file there.
     *
     * `sha256` is the original, and it alone is the integrity claim D3 prints —
     * a report's seal never rests on an image the client generated. The preview
     * is hashed too (`thumb_sha256`) for a different reason: it is what the AI
     * looks at, so the pipeline re-checks it before sending, and the approval is
     * then bound to the exact preview that is served (R5).
     */
    const hasPreviewSlot = row.kind === "photo" || row.kind === "video";
    const uploadThumbKey = hasPreviewSlot ? uploadPreviewKey(uploadKey) : null;
    let preview: { sha256: string; etag: string | null } | null = null;
    if (dto.thumbUploaded && uploadThumbKey) {
      preview = await this.readPreview(evidenceId, uploadThumbKey);
    }

    // ── 3. Move the verified bytes where no PUT URL reaches ─────────────────
    const sealedKeys = sealedKeysFor(uploadKey);
    const sealedThumbKey = preview ? sealedKeys.preview : null;
    try {
      await s3Service.copyObject(uploadKey, sealedKeys.original, { ifMatchEtag: original.etag });
      if (preview && uploadThumbKey) {
        await s3Service.copyObject(uploadThumbKey, sealedKeys.preview, { ifMatchEtag: preview.etag });
      }
    } catch (err) {
      // Not half-moved: the row stays on its upload keys, marked failed, and
      // whatever was copied is removed.
      await this.deleteObject(sealedKeys.original, sealedThumbKey);
      const winner = await this.failUnlessSealed(row.id);
      if (winner) return this.toView(winner, { audience: "owner" });
      logger.warn("[evidence] could not move the verified file — refusing to seal", {
        evidenceId,
        message: err instanceof Error ? err.message : String(err),
      });
      throw badRequest(
        "That file changed or did not finish uploading, so it has not been sealed. Try attaching it again.",
      );
    }

    // ── 4. Seal, under the lock ─────────────────────────────────────────────
    let sealed: { row: ReportEvidence; runQueued: boolean; won: boolean };
    try {
      sealed = await this.sealLocked(userId, row, dto, {
        sha256: actualHash,
        bytes: actualBytes,
        storageKey: sealedKeys.original,
        thumbKey: sealedThumbKey,
        thumbSha256: preview?.sha256 ?? null,
      });
    } catch (err) {
      await this.deleteObject(sealedKeys.original, sealedThumbKey);
      throw err;
    }
    if (!sealed.won) {
      // A concurrent commit sealed it first; its keys are the row's, ours are spare.
      await this.deleteObject(sealedKeys.original, sealedThumbKey);
      return this.toView(sealed.row, { audience: "owner" });
    }

    // ── 5. The upload keys are referenced by nothing now ────────────────────
    await this.deleteObject(uploadKey, uploadThumbKey);

    if (sealed.runQueued) pokeModeration();
    logger.info("[evidence] sealed", {
      evidenceId,
      kind: sealed.row.kind,
      bytes: actualBytes,
      preview: Boolean(sealedThumbKey),
      recheckQueued: sealed.runQueued,
    });
    return this.toView(sealed.row, { audience: "owner" });
  }

  /**
   * Mark a commit's row `failed` — unless another commit has sealed it in the
   * meantime, in which case that sealed row is returned and must not be touched.
   * Commits race: a client retry can arrive while the first commit is still
   * running, and once the first one seals it deletes the upload keys the second
   * is still reading (step 5). An unconditional `failed` there would unseal a
   * sealed file.
   */
  private async failUnlessSealed(rowId: string): Promise<ReportEvidence | null> {
    const [changed] = await ReportEvidence.update(
      { upload_state: "failed" },
      { where: { id: rowId, upload_state: { [Op.ne]: "sealed" } } },
    );
    if (changed > 0) return null;
    return ReportEvidence.findOne({ where: { id: rowId, upload_state: "sealed" } });
  }

  /**
   * Read and hash an uploaded preview. Returns null — seal without a preview —
   * when it is missing, over `PREVIEW_MAX_BYTES`, or not a JPEG/PNG/WebP: a
   * preview is a convenience, and a file without one is still sealed (the AI
   * then cannot see it, so it waits for a moderator, D22).
   */
  private async readPreview(
    evidenceId: string,
    key: string,
  ): Promise<{ sha256: string; etag: string | null } | null> {
    try {
      const got = await s3Service.getObject(key, { maxBytes: PREVIEW_MAX_BYTES });
      const type = sniffMediaType(got.bytes);
      if (!type || !PREVIEW_MEDIA_TYPES.has(type)) {
        logger.warn("[evidence] preview is not an image — sealing without it", { evidenceId });
        return null;
      }
      return { sha256: sha256Hex(got.bytes), etag: got.etag };
    } catch (err) {
      logger.warn("[evidence] could not read the preview — sealing without it", {
        evidenceId,
        message: err instanceof Error ? err.message : String(err),
      });
      return null;
    }
  }

  /**
   * Step 4 of `commit`: lock the parent (the same row presign and filing lock,
   * §7.1), re-read the file row, and seal it onto the sealed keys. `won` is
   * false when another commit sealed it first — that row is returned as is.
   */
  private async sealLocked(
    userId: string,
    row: ReportEvidence,
    dto: { capturedAt?: string; durationMs?: number },
    seal: {
      sha256: string;
      bytes: number;
      storageKey: string;
      thumbKey: string | null;
      thumbSha256: string | null;
    },
  ): Promise<{ row: ReportEvidence; runQueued: boolean; won: boolean }> {
    return lockedTransaction(async (transaction) => {
      // The parent first — the same row presign and filing lock (§7.1).
      let report: Report | null = null;
      if (row.draft_id) {
        const draft = await ReportDraft.findOne({
          where: { id: row.draft_id, user_id: userId },
          transaction,
          lock: transaction.LOCK.UPDATE,
        });
        if (!draft) throw notFound(DRAFT_GONE);
      } else {
        report = await Report.findOne({
          where: { id: row.report_id as string, user_id: userId },
          transaction,
          lock: transaction.LOCK.UPDATE,
        });
        if (!report || report.deleted_at) throw notFound(REPORT_GONE);
      }

      const locked = await ReportEvidence.findOne({
        where: { id: row.id, user_id: userId },
        transaction,
        lock: transaction.LOCK.UPDATE,
      });
      if (!locked) throw badRequest("That upload is not recognised.");
      if (locked.upload_state === "sealed") return { row: locked, runQueued: false, won: false };
      if (
        locked.draft_id !== row.draft_id ||
        locked.report_id !== row.report_id ||
        locked.storage_key !== row.storage_key
      ) {
        throw new HttpError("That file moved while it was being sealed. Try again.", 409);
      }

      await locked.update(
        {
          sha256: seal.sha256,
          bytes: seal.bytes,
          captured_at: dto.capturedAt ?? locked.captured_at,
          duration_ms: dto.durationMs ?? locked.duration_ms,
          // The sealed copies — no presigned PUT covers these keys (R5).
          storage_key: seal.storageKey,
          thumb_key: seal.thumbKey,
          thumb_sha256: seal.thumbSha256,
          upload_state: "sealed",
          sealed_at: nowIso(),
          // The client strips EXIF before upload; recorded honestly either way.
          metadata_scrubbed: locked.kind === "photo" || locked.kind === "video",
        },
        { transaction },
      );

      const runQueued = report ? await this.queueLateEvidenceRun(transaction, report, locked) : false;
      return { row: locked, runQueued, won: true };
    });
  }

  /**
   * A file sealed onto a report after filing (§5.1: "evidence committed on a
   * filed report → evidence `pending`, trigger `evidence`").
   *
   * Only for a moderated report that is `approved` or still `pending`; a held or
   * rejected one waits for a moderator, whose approval clears its pending files,
   * and a private one is never sent (D3).
   *
   *   • **pending, with a run queued** — nothing to add: that run reads every
   *     pending file of the report when a worker claims it.
   *   • **pending, its run already claimed** — that run listed the files before
   *     this one was sealed, so a run is queued; once the report is published it
   *     assesses the file (and if the report is held instead, the run is dropped
   *     and the file waits for the moderator). If the report is still waiting
   *     for its resubmission check, that run is `resubmitted`, not `evidence`
   *     (review R1): an `evidence` run on a pending report is a content decision
   *     the AI alone may approve, so a photo added while a resubmitted run was in
   *     flight used to republish a report a human had rejected.
   *   • **approved** — an `evidence` run, merged into one already queued. A
   *     queued run of any other kind (a `flagged` re-check, a moderator's re-run)
   *     is not merged into: the trigger decides what the pipeline checks, and
   *     every run on a report reads its pending files anyway.
   *
   * An urgent report's run keeps the urgent priority and the short retry budget
   * the filing gave it (review R2), so an outage still reaches a human in about
   * a minute (D5/D21). The rule is the pure `planLateEvidenceRun`.
   */
  private async queueLateEvidenceRun(
    transaction: Transaction,
    report: Report,
    row: ReportEvidence,
  ): Promise<boolean> {
    const eligible = planLateEvidenceRun({
      moderated: needsModeration(report),
      reportState: report.moderation_state,
      fileState: row.moderation_state,
      urgent: report.urgent,
      queuedTrigger: null,
      awaitingResubmissionCheck: false,
    });
    if (!eligible) return false;

    const queued = await sequelize.query<{ trigger: string }>(
      `SELECT "trigger" FROM moderation_runs
        WHERE target_type = 'report' AND target_id = :reportId AND status = 'queued'
        LIMIT 1`,
      { replacements: { reportId: report.id }, type: QueryTypes.SELECT, transaction },
    );
    const queuedTrigger = queued[0]?.trigger ?? null;
    const awaiting =
      report.moderation_state === "pending" && queuedTrigger === null
        ? await awaitsResubmissionCheck(transaction, report)
        : false;

    const plan = planLateEvidenceRun({
      moderated: true,
      reportState: report.moderation_state,
      fileState: row.moderation_state,
      urgent: report.urgent,
      queuedTrigger,
      awaitingResubmissionCheck: awaiting,
    });
    if (!plan) return false;

    await enqueueRun(transaction, {
      targetType: "report",
      targetId: report.id,
      reportId: report.id,
      contentVersion: report.content_version,
      trigger: plan.trigger,
      priority: plan.priority,
      maxAttempts: maxAttemptsFor(plan.urgent),
    });
    return true;
  }

  /**
   * Remove an attachment before the report is filed. Only the caller's own file
   * on their own, not-yet-filed draft — under the draft lock, so a file cannot
   * disappear from under a filing in progress.
   */
  async remove(userId: string, evidenceId: string): Promise<boolean> {
    const row = await ReportEvidence.findOne({ where: { id: evidenceId, user_id: userId } });
    if (!row) return false;
    // Only a draft's files can be removed: once filed, evidence is append-only so
    // the D3 integrity claims stay true.
    if (row.report_id) {
      throw badRequest(
        "A filed report's evidence cannot be removed. Delete the report instead.",
      );
    }

    const removed = await lockedTransaction(async (transaction) => {
      if (row.draft_id) {
        const draft = await ReportDraft.findOne({
          where: { id: row.draft_id, user_id: userId },
          transaction,
          lock: transaction.LOCK.UPDATE,
        });
        if (!draft) throw notFound(DRAFT_GONE);
      }
      const locked = await ReportEvidence.findOne({
        where: { id: evidenceId, user_id: userId },
        transaction,
        lock: transaction.LOCK.UPDATE,
      });
      if (!locked) return null;
      if (locked.report_id) {
        throw badRequest(
          "A filed report's evidence cannot be removed. Delete the report instead.",
        );
      }
      await locked.destroy({ transaction });
      return locked;
    });
    if (!removed) return false;

    // After the commit: a failed object delete leaves an orphan in the bucket,
    // never a row pointing at nothing.
    await this.deleteObjectsOf(removed);
    return true;
  }

  /**
   * Best-effort removal of every object a file row may own. A sealed row owns
   * its sealed keys; an unsealed one still sits on its upload keys, and its
   * preview (if the client PUT one) is at an upload key `thumb_key` never
   * recorded (R5).
   */
  async deleteObjectsOf(
    row: Pick<ReportEvidence, "storage_key" | "thumb_key" | "upload_state" | "kind">,
  ): Promise<void> {
    const previewKey =
      row.thumb_key ??
      (row.upload_state !== "sealed" && (row.kind === "photo" || row.kind === "video")
        ? uploadPreviewKey(row.storage_key)
        : null);
    await this.deleteObject(row.storage_key, previewKey);
  }

  /** Best-effort object removal. A missing object is not an error. */
  async deleteObject(storageKey: string, thumbKey?: string | null): Promise<void> {
    if (!this.isStorageReady) return;
    await s3Service.deleteObject(storageKey).catch(() => {});
    if (thumbKey) await s3Service.deleteObject(thumbKey).catch(() => {});
  }

  /**
   * Every file on a report a viewer may know about, presigned where they may
   * open it (D22, §7.3). The owner gets every file with its state; anyone else
   * gets approved files with the URLs their approval covers (both, or the
   * preview alone — R5) and pending ones as "Awaiting review".
   */
  async listForReport(reportId: string, options: { owner: boolean }): Promise<EvidenceView[]> {
    const rows = await ReportEvidence.findAll({
      where: { report_id: reportId },
      order: [["sort_order", "ASC"]],
    });
    const audience: EvidenceAudience = options.owner ? "owner" : "member";
    const listed = rows.filter((row) => evidenceAccessFor(row, options.owner) !== "hidden");
    return Promise.all(listed.map((row) => this.toView(row, { audience })));
  }

  /**
   * Every file on the caller's own draft, for the C5 attached list. A draft that
   * is not theirs is a 404 — this used to answer for any draft UUID (§7.9).
   */
  async listForDraft(userId: string, draftId: string): Promise<EvidenceView[]> {
    const draft = await ReportDraft.findOne({
      where: { id: draftId, user_id: userId },
      attributes: ["id"],
    });
    if (!draft) throw notFound(DRAFT_GONE);
    const rows = await ReportEvidence.findAll({
      where: { draft_id: draftId },
      order: [["sort_order", "ASC"]],
    });
    return Promise.all(rows.map((row) => this.toView(row, { audience: "owner" })));
  }

  /**
   * Project one row, minting short-lived read URLs.
   *
   * Evidence is never public: a leaked link expires instead of remaining an open
   * hole, which is why the URL is per-request rather than stored. The default
   * audience is staff (everything). For a `member` audience the D22 rule is
   * applied *here*, not only by the caller (review R5 — the feed used to project
   * a lead image with the staff default and hand every viewer the original):
   *
   *   • `full`           — `url` and `thumbUrl`;
   *   • `thumbnail_only` — `thumbUrl` alone, `fullResolutionPending: true`;
   *   • pending/hidden   — no URLs (`pendingReview` for a pending file).
   */
  async toView(
    row: ReportEvidence,
    options: { audience?: EvidenceAudience } = {},
  ): Promise<EvidenceView> {
    const audience = options.audience ?? "staff";
    const access: EvidenceAccess = audience === "member" ? evidenceAccessFor(row, false) : "full";
    if (access === "pending_review" || access === "hidden") {
      const withheld = this.pendingReviewView(row);
      if (access === "hidden") delete withheld.pendingReview;
      return withheld;
    }

    let url: string | null = null;
    let thumbUrl: string | null = null;
    if (this.isStorageReady && row.upload_state === "sealed") {
      if (access === "full") {
        url = await s3Service.getPresignedDownloadUrl(row.storage_key).catch(() => null);
      }
      if (row.thumb_key) {
        thumbUrl = await s3Service.getPresignedDownloadUrl(row.thumb_key).catch(() => null);
      }
    }

    const view: EvidenceView = {
      id: row.id,
      kind: row.kind,
      mime: row.mime,
      bytes: row.bytes,
      durationMs: row.duration_ms,
      capturedAt: row.captured_at,
      sealedAt: row.sealed_at,
      uploadState: row.upload_state,
      url,
      thumbUrl,
    };
    if (access === "thumbnail_only") view.fullResolutionPending = true;
    if (audience !== "member") view.moderationState = row.moderation_state;
    return view;
  }

  /** A file a non-owner may know exists but not open yet — no URLs at all. */
  private pendingReviewView(row: ReportEvidence): EvidenceView {
    return {
      id: row.id,
      kind: row.kind,
      mime: row.mime,
      bytes: row.bytes,
      durationMs: row.duration_ms,
      capturedAt: row.captured_at,
      sealedAt: row.sealed_at,
      uploadState: row.upload_state,
      url: null,
      thumbUrl: null,
      pendingReview: true,
    };
  }

  /** "Video · 0:42 · 24.8 MB" — the label C5, C9 and D3 print. */
  describe(row: ReportEvidence): string {
    const parts: string[] = [KIND_LABELS[row.kind]];
    if (row.duration_ms) parts.push(formatDuration(row.duration_ms));
    if (row.bytes) parts.push(formatBytes(row.bytes));
    return parts.join(" · ");
  }
}

export const evidenceService = new EvidenceService();
export default evidenceService;
