/**
 * Declare package-visibility for `mailto:` intents on Android.
 *
 * Android 11+ (API 30+) hides other apps' intent filters from `canOpenURL`
 * unless the querying app explicitly declares that it needs to see them, via
 * a `<queries>` block in AndroidManifest.xml. Without this entry,
 * `Linking.canOpenURL("mailto:...")` returns `false` even when a mail app
 * (Gmail, Outlook, the stock mail app, ...) is installed and would happily
 * handle it — which is exactly what made app/profile/contact.tsx's "Send"
 * button report "No email app is set up on this device" on a device that
 * had Gmail configured.
 *
 * `android/` is gitignored and regenerated by `expo prebuild`, so this has
 * to be a config plugin (see plugins/withIPhoneOnlyDestinations.js for the
 * same reasoning on the iOS side) rather than a one-off manifest edit.
 */

const { withAndroidManifest } = require("@expo/config-plugins");

module.exports = function withAndroidMailtoQuery(config) {
  return withAndroidManifest(config, (cfg) => {
    const manifest = cfg.modResults.manifest;
    manifest.queries = manifest.queries ?? [];
    if (!Array.isArray(manifest.queries)) manifest.queries = [manifest.queries];

    let queriesBlock = manifest.queries[0];
    if (!queriesBlock) {
      queriesBlock = {};
      manifest.queries.push(queriesBlock);
    }
    queriesBlock.intent = queriesBlock.intent ?? [];

    const alreadyDeclared = queriesBlock.intent.some(
      (entry) => entry?.data?.[0]?.$?.["android:scheme"] === "mailto",
    );
    if (alreadyDeclared) return cfg;

    queriesBlock.intent.push({
      action: [{ $: { "android:name": "android.intent.action.SENDTO" } }],
      data: [{ $: { "android:scheme": "mailto" } }],
    });

    return cfg;
  });
};
