/**
 * Enable UIKit's scene-based lifecycle for iOS builds.
 *
 * Newer iOS SDKs require apps to adopt UIScene. The Expo/RN template this
 * project was generated from still launches React Native directly from
 * AppDelegate, so local Xcode builds can crash at startup with:
 *
 * "UIScene life cycle is required for apps built with this SDK."
 *
 * Keep this as a config plugin because ios/ can be regenerated by prebuild.
 */

const { withDangerousMod, withInfoPlist, withXcodeProject } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const APP_DELEGATE_SWIFT = "AppDelegate.swift";
const SCENE_DELEGATE_SWIFT = "SceneDelegate.swift";

const SCENE_DELEGATE_SOURCE = `import UIKit

class SceneDelegate: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard let windowScene = scene as? UIWindowScene else {
      return
    }

    guard
      let appDelegate = UIApplication.shared.delegate as? AppDelegate,
      let factory = appDelegate.reactNativeFactory
    else {
      return
    }

#if DEBUG
    if let existingWindow = appDelegate.window,
       existingWindow.rootViewController != nil {
      existingWindow.windowScene = windowScene
      existingWindow.makeKeyAndVisible()
      self.window = existingWindow
      return
    }
#endif

    let window = UIWindow(windowScene: windowScene)
    self.window = window
    window.makeKeyAndVisible()

    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: nil
    )
  }
}
`;

const DEV_LAUNCHER_WINDOW_BOOTSTRAP = `#if DEBUG
    // Expo Dev Launcher expects a key window and React Native bridge before
    // super.application(...). Release/App Store builds start React Native from
    // SceneDelegate only, which satisfies UIKit's scene lifecycle requirement.
    if window == nil {
      window = UIWindow(frame: UIScreen.main.bounds)
    }

    window?.makeKeyAndVisible()

    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: launchOptions
    )
#endif

`;

function findAppSourceGroup(project) {
  const groups = project.hash.project.objects.PBXGroup ?? {};

  for (const [key, group] of Object.entries(groups)) {
    if (!group || typeof group !== "object") continue;

    const children = group.children ?? [];
    if (children.some((child) => child?.comment === APP_DELEGATE_SWIFT)) {
      return key;
    }
  }

  return undefined;
}

function removeLegacyWindowBootstrap(source) {
  return source.replace(
    /\n#if os\(iOS\) \|\| os\(tvOS\)\n    window = UIWindow\(frame: UIScreen\.main\.bounds\)\n    factory\.startReactNative\(\n      withModuleName: "main",\n      in: window,\n      launchOptions: launchOptions\)\n#endif\n/,
    "\n",
  );
}

function ensureDevLauncherWindowBootstrap(source) {
  const cleaned = source.replace(
    /\n#if DEBUG\n    \/\/ Expo Dev Launcher [\s\S]*?^#endif\n/m,
    "\n",
  );

  return cleaned.replace(
    "    return super.application(application, didFinishLaunchingWithOptions: launchOptions)",
    DEV_LAUNCHER_WINDOW_BOOTSTRAP +
      "    return super.application(application, didFinishLaunchingWithOptions: launchOptions)",
  );
}

module.exports = function withIosSceneLifecycle(config) {
  config = withInfoPlist(config, (cfg) => {
    cfg.modResults.UIApplicationSceneManifest = {
      UIApplicationSupportsMultipleScenes: false,
      UISceneConfigurations: {
        UIWindowSceneSessionRoleApplication: [
          {
            UISceneConfigurationName: "Default Configuration",
            UISceneDelegateClassName: "$(PRODUCT_MODULE_NAME).SceneDelegate",
          },
        ],
      },
    };

    return cfg;
  });

  config = withDangerousMod(config, [
    "ios",
    (cfg) => {
      const iosRoot = cfg.modRequest.platformProjectRoot;
      const appRoot = path.join(iosRoot, cfg.modRequest.projectName);

      const appDelegatePath = path.join(appRoot, APP_DELEGATE_SWIFT);
      if (fs.existsSync(appDelegatePath)) {
        const next = ensureDevLauncherWindowBootstrap(
          removeLegacyWindowBootstrap(fs.readFileSync(appDelegatePath, "utf8")),
        );
        fs.writeFileSync(appDelegatePath, next);
      }

      fs.writeFileSync(path.join(appRoot, SCENE_DELEGATE_SWIFT), SCENE_DELEGATE_SOURCE);

      return cfg;
    },
  ]);

  return withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;
    const appSourceGroup = findAppSourceGroup(project);
    const sceneDelegateProjectPath = `${cfg.modRequest.projectName}/${SCENE_DELEGATE_SWIFT}`;

    if (!project.hasFile(sceneDelegateProjectPath)) {
      project.addSourceFile(sceneDelegateProjectPath, undefined, appSourceGroup);
    }

    return cfg;
  });
};
