/**
 * Keep generated Pods settings aligned with the app target.
 *
 * A few pods declare old iOS deployment targets in their podspecs, which makes
 * Xcode warn even though the app itself targets a newer iOS version. Hermes also
 * ships a script phase without outputs, which Xcode warns about unless it is
 * explicitly marked as always out of date.
 *
 * Keep this as a config plugin because ios/ is generated by prebuild.
 */

const fs = require("fs");
const path = require("path");
const { withDangerousMod } = require("@expo/config-plugins");

const DEPLOYMENT_TARGET_SNIPPET =
  "config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = podfile_properties['ios.deploymentTarget'] || '17.0'";
const HERMES_SNIPPET = "phase.always_out_of_date = '1'";

const PODS_BUILD_FIXES = `
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        ${DEPLOYMENT_TARGET_SNIPPET}
      end

      target.shell_script_build_phases.each do |phase|
        next unless phase.name == '[CP-User] [Hermes] Replace Hermes for the right configuration, if needed'

        ${HERMES_SNIPPET}
      end
    end
`;

function patchPodfile(contents) {
  if (contents.includes(DEPLOYMENT_TARGET_SNIPPET) && contents.includes(HERMES_SNIPPET)) {
    return contents;
  }

  const reactNativePostInstallMatch =
    /(\n\s+react_native_post_install\(\n[\s\S]*?\n\s+\)\n)/m;

  if (!reactNativePostInstallMatch.test(contents)) {
    throw new Error("Unable to find react_native_post_install block in ios/Podfile");
  }

  return contents.replace(reactNativePostInstallMatch, `$1${PODS_BUILD_FIXES}`);
}

module.exports = function withIosPodsBuildFixes(config) {
  return withDangerousMod(config, [
    "ios",
    (cfg) => {
      const podfilePath = path.join(cfg.modRequest.platformProjectRoot, "Podfile");
      const contents = fs.readFileSync(podfilePath, "utf8");
      const patched = patchPodfile(contents);

      if (patched !== contents) {
        fs.writeFileSync(podfilePath, patched);
      }

      return cfg;
    },
  ]);
};
