/**
 * Name every Android APK BlackNexa_{environment}_{buildType}_v{version}_{DDMMYYYY}.apk.
 *
 * `android/` is gitignored and regenerated by `expo prebuild` (see
 * plugins/withAndroidReleaseSigning.js), so the naming rule is added to
 * app/build.gradle here rather than edited in by hand.
 *
 * The hook deliberately holds no version or environment of its own: at build
 * time it runs scripts/android-apk-name.js, which reads both from
 * app.config.ts. A version bump there therefore reaches the file name without
 * another prebuild. It renames the APK Gradle writes, so it applies however the
 * build is started: `npm run apk:*`, `./gradlew assemble*`, Android Studio,
 * `expo run:android` (which finds the renamed file through Gradle's
 * output-metadata.json) and EAS Build. App bundles (.aab) keep their names.
 *
 * If the script fails, the build carries on under Gradle's default names and
 * says why, rather than failing a build over its file name.
 */

const { withAppBuildGradle } = require("@expo/config-plugins");

const MARKER = "// @generated blacknexa-apk-naming";

const APK_NAMING_BLOCK = `
${MARKER} (plugins/withAndroidApkNaming.js)
// BlackNexa_{environment}_{buildType}_v{version}_{DDMMYYYY}.apk, with version and
// environment read from app.config.ts at build time by scripts/android-apk-name.js.
def blackNexaApkNames = null
android.applicationVariants.all { variant ->
    if (blackNexaApkNames == null) {
        blackNexaApkNames = [:]
        def appRoot = rootDir.getAbsoluteFile().getParentFile()
        try {
            def stdout = new StringBuilder()
            def stderr = new StringBuilder()
            def proc = ["node", new File(appRoot, "scripts/android-apk-name.js").absolutePath].execute(null, appRoot)
            proc.waitForProcessOutput(stdout, stderr)
            if (proc.exitValue() == 0) {
                def lastLine = stdout.toString().readLines().findAll { it.trim() }.last()
                blackNexaApkNames = new groovy.json.JsonSlurper().parseText(lastLine)
            } else {
                logger.warn("BlackNexa APK naming skipped, default APK names used: " + stderr.toString().trim())
            }
        } catch (Exception e) {
            logger.warn("BlackNexa APK naming skipped, default APK names used: " + e.message)
        }
    }
    def apkName = blackNexaApkNames[variant.buildType.name]
    if (apkName) {
        variant.outputs.all { outputFileName = apkName }
        logger.lifecycle("BlackNexa APK (" + variant.buildType.name + "): " + apkName)
    }
}
`;

module.exports = function withAndroidApkNaming(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (!cfg.modResults.contents.includes(MARKER)) {
      cfg.modResults.contents = `${cfg.modResults.contents.trimEnd()}\n${APK_NAMING_BLOCK}`;
    }
    return cfg;
  });
};
