/**
 * Disable Xcode user-script sandboxing for the app target.
 *
 * React Native's debug-device flow writes `ip.txt` into the built .app bundle
 * so physical devices can find the Metro server. With Xcode's user script
 * sandbox enabled, that write is denied:
 *
 * Sandbox: bash(...) deny(1) file-write-create .../BlackNexaDev.app/ip.txt
 *
 * Keep this as a config plugin because ios/ is generated by prebuild.
 */

const { withXcodeProject } = require("@expo/config-plugins");

module.exports = function withIosUserScriptSandboxingDisabled(config) {
  return withXcodeProject(config, (cfg) => {
    const configurations = cfg.modResults.pbxXCBuildConfigurationSection();

    for (const key of Object.keys(configurations)) {
      const buildSettings = configurations[key]?.buildSettings;
      if (!buildSettings || typeof buildSettings !== "object") continue;
      if (!buildSettings.PRODUCT_BUNDLE_IDENTIFIER) continue;

      buildSettings.ENABLE_USER_SCRIPT_SANDBOXING = "NO";
    }

    return cfg;
  });
};
