/**
 * Wire up release-build signing from android/keystore.properties, when present.
 *
 * `android/` is gitignored and regenerated by `expo prebuild` (see
 * plugins/withIPhoneOnlyDestinations.js for the same reasoning on iOS), so a
 * one-off edit to build.gradle's signingConfigs is silently discarded by the
 * next prebuild/EAS cloud build — this happened twice already. This plugin
 * makes the fix survive regeneration.
 *
 * keystore.properties itself is a local secret file (gitignored, not
 * generated by this plugin) — copy android/keystore.properties.example to
 * android/keystore.properties and fill in the real values after any fresh
 * checkout or `expo prebuild --clean`. Without it, this plugin leaves the
 * release build type on the debug keystore, same as stock Expo.
 */

const { withAppBuildGradle } = require("@expo/config-plugins");

const KEYSTORE_PROPERTIES_LOADER = `
def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}
`;

module.exports = function withAndroidReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    let contents = cfg.modResults.contents;

    if (!contents.includes('rootProject.file("keystore.properties")')) {
      contents = contents.replace(
        /android\s*\{/,
        `${KEYSTORE_PROPERTIES_LOADER}\nandroid {`,
      );
    }

    if (!contents.includes("signingConfigs.release")) {
      contents = contents.replace(
        /signingConfigs\s*\{\n(\s*debug\s*\{[^}]*\}\n)/,
        `signingConfigs {\n$1        if (keystorePropertiesFile.exists()) {\n            release {\n                storeFile rootProject.file(keystoreProperties['storeFile'])\n                storePassword keystoreProperties['storePassword']\n                keyAlias keystoreProperties['keyAlias']\n                keyPassword keystoreProperties['keyPassword']\n            }\n        }\n`,
      );
    }

    if (contents.includes("release {\n            // Caution!")) {
      contents = contents.replace(
        /release \{\n(\s*)\/\/ Caution![^\n]*\n(\s*)\/\/ see[^\n]*\n(\s*)signingConfig signingConfigs\.debug/,
        `release {\n$1// Falls back to the debug keystore if android/keystore.properties is absent.\n$3signingConfig keystorePropertiesFile.exists() ? signingConfigs.release : signingConfigs.debug`,
      );
    }

    cfg.modResults.contents = contents;
    return cfg;
  });
};
